version: 0.2

phases:
  install:
    commands:
      - pip install -q aws-sam-cli --upgrade
  build:
    commands:
      - make build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
